### ISSUE TITLE
Client/Server api version mismatch

### ISSUE THREAD

**Issue by flingjie** [MystenLabs/walrus-sites#265]
### What happened?

Updating the Walrus Site object on Sui ... 2024-10-20T12:25:36.124304Z  WARN sui_sdk::wallet_context: Client/Server api version mismatch, client api version : 1.34.2, server api version : 1.35.1
[warn] Client/Server api version mismatch, client api version : 1.34.2, server api version : 1.35.1

### Search terms

 /issues?q=is:issue is:open version

### Steps to reproduce

Example:
1. Publish site with the following contents: [./target/release/site-builder publish ./examples/snake --epochs 100]

### Version

- [X] `walrus` and `site-builder` are up to date.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by mario4tier** [comment]
You can ignore this (it is not a bug).

It happens when the client version (the Sui SDK in the Walrus binaries) is a different version than the RPC servers.

You will observe this from time to time because the network constantly updates... and it is typically not cause for concern between small version differences.

Keep also in mind that not all RPC servers runs the same version, so there is no way to "perfectly" always eliminate these warnings... just keep your client up to date with latest like you already did :slightly_smiling_face:
