### ISSUE TITLE
Web Manifest icons are not loaded by Walrus Sites

### ISSUE THREAD

**Issue by kkomelin** [MystenLabs/walrus-sites#90]
After deploying my app to Walrus Sites https://suidappstarter.walrus.site/, I noticed an issue with loading PNG app icons, reported in the App Manifest section:

![Screenshot from 2024-06-19 11-05-36](https://github.com/MystenLabs/walrus-sites/assets/755066/eac8370d-56fa-446b-8cf0-741ee68a497d)

However, the PNG files are accessible directly.

Site: https://suidappstarter.walrus.site/
Web manifest: https://suidappstarter.walrus.site/webmanifest.json
Icon: https://suidappstarter.walrus.site/android-chrome-192x192.png

**Comment by giac-mysten** [comment]
This is very interesting, thanks @kkomelin for the report. 

The problem here seems to be that the browser loads the resources in the app manifest from outside the scope of the service worker. Unfortunately, this means that it will not be able to load the icons, because it is the service worker that communicates with Sui and Walrus and fetches the icon from the store.

I will think about it a bit more and ask around, but I think this may be a fundamental limitation of the "service-worker approach" to Walrus Sites. If/when we get around to creating a "server-side portal" (see the [high level description in the documentation](https://docs.walrus.site/walrus-sites/overview.html#the-site-rendering-path)) this will surely work.

**Comment by kkomelin** [comment]
Thank you @giac-mysten. That's right. I will think about what we could do for a workaround too.

**Comment by giac-mysten** [comment]
Thanks! Please report back here if you find a satisfactory solution. I'll do the same :)

**Comment by giac-mysten** [comment]
Closing now, as we can now at least serve this from the server side portal. The issue persists on service worker portals, but we are assuming this is unavoidable.

**Comment by kkomelin** [comment]
Alright, thanks @giac-mysten
